### PR TITLE
Use new sdk implementation

### PR DESCRIPTION
**Pull request by smacker**

### CODE REVIEW

**Review by abeaumont — COMMENTED** [review]
CI is failing, apparently due to some dependency missing...

**Comment by erizocosmico** [comment]
Says ava is not installed. Ava is in `devDependencies`, perhaps we need to set `--production=false`, though it's very odd that it takes it as a prod env https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-production-true-false

**Comment by smacker** [comment]
wow. I didn't know yarn takes environment variable, that's why it works fine for me.

**Comment by erizocosmico** [comment]
Aw, damn. It had nothing to do with that. turns out is this line: https://github.com/bblfsh/typescript-driver/pull/4/files#diff-b171f633d1acd25947e11abc14901951R24 which obviously does not work because ava is not installed globally in the CI. Should be `./node_modules/ava/yada/yada/avabinary` instead of just `ava`. Either that or `yarn global add ava`

**Comment by smacker** [comment]
@erizocosmico thanks but yarn runs command from node_modules in script section correctly, same as npm. The problem was that locally I had "dirty" directory (it contained node_modules already), so after mount inside docker everything worked fine. Not a case for a CI.

There was also a problem with nodejs version (couldn't reproduce locally), so I set fixed version. Actually it was better to do from a start. Relying on latest tag always cause problems in future.

**Review by abeaumont — APPROVED** [review]

**Comment by abeaumont** [comment]
Great work @smacker, thanks!

**Pull request merged**
